# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev libpng-dev
      - run: sudo docker-php-ext-install bcmath
      - run: sudo docker-php-ext-install gd

      # Composer
      - restore_cache:
          keys:
          - composer-dependencies-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: composer-dependencies-{{ checksum "composer.json" }}

      # NPM
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # compile assets properly
      - run: npm run dev

      # run tests_core script
      - run: php scripts/test_core.php

      # run entire phpunit test suite
      - run:
          name: "Run test suite"
          command: vendor/bin/phpunit -d memory_limit=512M --configuration phpunit.xml --stop-on-failure
